// apps/site/src/examples/solid/AutoLayoutDemo.tsx
// Solid — one arrange call is one undo step. Direction is a signal passed to runAutoLayout.
import { createSignal } from 'solid-js'
import { xenolith } from '@xenolithengine/graph-solid'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupAutoLayout, runAutoLayout } from '@xenolithengine/demo/auto-layout'

type Direction = 'LR' | 'TB'

function btn(on: boolean, disabled: boolean): string {
  return `font:inherit;font-size:12px;padding:6px 12px;border-radius:6px;cursor:${disabled ? 'default' : 'pointer'};opacity:${disabled ? 0.4 : 1};border:1px solid ${on ? 'var(--xeno-accent)' : 'var(--xeno-border)'};background:${on ? 'var(--xeno-accent)' : 'var(--xeno-panel)'};color:${on ? 'var(--xeno-canvas)' : 'var(--xeno-text)'};`
}

export function AutoLayoutDemo() {
  const [editor, setEditor] = createSignal<XenolithEditor | null>(null)
  const [dir, setDir] = createSignal<Direction>('LR')
  const [busy, setBusy] = createSignal(false)

  async function arrange(next: Direction = dir()): Promise<void> {
    const e = editor()
    if (!e || busy()) return
    setBusy(true)
    try { await runAutoLayout(e, { direction: next }) } finally { setBusy(false) }
  }
  async function flip(next: Direction): Promise<void> {
    setDir(next)
    await arrange(next)
  }

  return (
    <div
      use:xenolith={{ resizeToWindow: false }}
      on:ready={(e) => { setEditor(e.detail); setupAutoLayout(e.detail) }}
      style="position:absolute;inset:0"
    >
      <div style="position:absolute;top:12px;left:12px;z-index:5;display:flex;gap:6px;padding:6px;background:var(--xeno-panel);border:1px solid var(--xeno-border);border-radius:10px;">
        <button type="button" style={btn(true, busy())} disabled={busy()} onClick={() => void arrange()}>{busy() ? 'Arranging…' : 'Auto-arrange'}</button>
        <button type="button" style={btn(dir() === 'LR', busy())} disabled={busy()} onClick={() => void flip('LR')}>LR</button>
        <button type="button" style={btn(dir() === 'TB', busy())} disabled={busy()} onClick={() => void flip('TB')}>TB</button>
      </div>
    </div>
  )
}

// apps/site/src/examples/angular/AutoLayoutDemo.component.ts
// Angular — one arrange call is one undo step. Direction is a signal passed to runAutoLayout.
import { AfterViewInit, Component, ElementRef, OnDestroy, inject, signal, viewChild } from '@angular/core'
import { XenolithGraphService } from '@xenolithengine/graph-angular'
import { setupAutoLayout, runAutoLayout } from '@xenolithengine/demo/auto-layout'

type Direction = 'LR' | 'TB'

@Component({
  selector: 'auto-layout-demo',
  standalone: true,
  providers: [XenolithGraphService],
  template: `
    <div style="position:absolute;inset:0;">
      <div #host class="xeno" style="position:absolute;inset:0;"></div>
      <div class="card">
        <button type="button" class="btn on" [disabled]="busy()" (click)="arrange()">
          {{ busy() ? 'Arranging…' : 'Auto-arrange' }}
        </button>
        <button type="button" class="btn" [class.on]="dir() === 'LR'" [disabled]="busy()" (click)="flip('LR')">LR</button>
        <button type="button" class="btn" [class.on]="dir() === 'TB'" [disabled]="busy()" (click)="flip('TB')">TB</button>
      </div>
    </div>
  `,
  styles: [`
    .card { position:absolute; top:12px; left:12px; z-index:5; display:flex; gap:6px; padding:6px;
      background:var(--xeno-panel,#1d1d1d); border:1px solid var(--xeno-border,#333);
      border-radius:10px; font:13px system-ui,sans-serif; }
    .btn { font:inherit; font-size:12px; padding:6px 12px; cursor:pointer; border-radius:6px;
      border:1px solid var(--xeno-border,#333); background:var(--xeno-panel,#1d1d1d);
      color:var(--xeno-text,#cfcfcf); }
    .btn.on { border-color:var(--xeno-accent,#FCB400); background:var(--xeno-accent,#FCB400);
      color:var(--xeno-canvas,#111); }
    .btn:disabled { opacity:0.4; cursor:default; }
  `],
})
export class AutoLayoutDemoComponent implements AfterViewInit, OnDestroy {
  private graph = inject(XenolithGraphService)
  private host = viewChild.required<ElementRef<HTMLDivElement>>('host')
  dir = signal<Direction>('LR')
  busy = signal(false)

  async ngAfterViewInit(): Promise<void> {
    const editor = await this.graph.mount(this.host().nativeElement, { resizeToWindow: false })
    setupAutoLayout(editor)
  }

  async arrange(next: Direction = this.dir()): Promise<void> {
    const editor = this.graph.editor
    if (!editor || this.busy()) return
    this.busy.set(true)
    try { await runAutoLayout(editor, { direction: next }) } finally { this.busy.set(false) }
  }

  async flip(next: Direction): Promise<void> {
    this.dir.set(next)
    await this.arrange(next)
  }

  ngOnDestroy(): void { this.graph.destroy() }
}
