// apps/demo-react/src/demos/PropertiesSidebarDemo.tsx
import { useEffect, useState } from 'react'
import { XenolithGraph, XenolithPanel, useEditor } from '@xenolithengine/graph-react'
import { setupPropertiesSidebar, PROPERTIES_SIDEBAR_NODE_ID } from '@xenolithengine/demo/properties-sidebar'
import { DemoStage } from '../Layout.js'

// Canon: sidebar open-state lives in the panel — only the panel needs it. Open/close are direct
// editor calls. The panel mounts AFTER `onReady` (Provider gates children on editor presence), so
// the auto-open effect runs once with a guaranteed-ready editor.

function SidebarPanel() {
  const editor = useEditor()
  const [open, setOpen] = useState(true)

  useEffect(() => {
    // Auto-open on mount so the demo lands with the panel visible — first impression matters.
    editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID)
  }, [editor])

  const toggle = (): void => {
    if (open) { editor.closeSidebar(); setOpen(false) }
    else      { editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID); setOpen(true) }
  }

  return (
    <XenolithPanel position="top-left" style={{ display: 'flex', gap: 6, padding: 6 }}>
      <button onClick={toggle} style={btn(open)}>{open ? 'Close sidebar' : 'Open sidebar'}</button>
    </XenolithPanel>
  )
}

/** Island: G4 — properties sidebar. */
export function PropertiesSidebarDemo() {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={setupPropertiesSidebar}>
        <SidebarPanel />
      </XenolithGraph>
    </DemoStage>
  )
}

const btn = (on: boolean): React.CSSProperties => ({
  padding: '6px 12px',
  fontSize: 12,
  borderRadius: 6,
  border: `1px solid ${on ? 'var(--xeno-accent, #FCB400)' : 'var(--xeno-border, #333)'}`,
  background: on ? 'var(--xeno-accent, #FCB400)' : 'transparent',
  color: on ? 'var(--xeno-canvas, #111)' : 'var(--xeno-text, #cfcfcf)',
  cursor: 'pointer',
})

// apps/site/src/examples/angular/PropertiesSidebarDemo.component.ts
// Angular standalone component — properties sidebar. Auto-open via the `(ready)` Output; toggle
// is a direct editor call. Sidebar open-state lives only in the component that drives the button.
import { Component, signal } from '@angular/core'
import { XenolithGraphComponent } from '@xenolithengine/graph-angular'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupPropertiesSidebar, PROPERTIES_SIDEBAR_NODE_ID } from '@xenolithengine/demo/properties-sidebar'

@Component({
  selector: 'properties-sidebar-demo',
  standalone: true,
  imports: [XenolithGraphComponent],
  template: `
    <div class="app" style="position:absolute;inset:0;">
      <xenolith-graph
        class="xeno"
        [resizeToWindow]="false"
        (ready)="onReady($event)">
      </xenolith-graph>

      <div data-xeno-panel class="panel">
        <button class="btn" [class.on]="open()" (click)="toggle()">
          {{ open() ? 'Close sidebar' : 'Open sidebar' }}
        </button>
      </div>
    </div>
  `,
  styles: [\`
    .panel { position:absolute; top:12px; left:12px; display:flex; gap:6px; padding:6px;
      background:var(--xeno-panel,#1d1d1d); border:1px solid var(--xeno-border,#333);
      border-radius:8px; font:12px Inter,system-ui,sans-serif; z-index:5; }
    .btn { padding:6px 12px; font-size:12px; cursor:pointer; border-radius:6px;
      border:1px solid var(--xeno-border,#333); background:transparent; color:var(--xeno-text,#cfcfcf); }
    .btn.on { border-color:var(--xeno-accent,#FCB400); background:var(--xeno-accent,#FCB400);
      color:var(--xeno-canvas,#111); }
  \`],
})
export class PropertiesSidebarDemoComponent {
  private editor: XenolithEditor | null = null
  open = signal(true)

  onReady(editor: XenolithEditor): void {
    this.editor = editor
    setupPropertiesSidebar(editor)
    editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID)
  }

  toggle(): void {
    if (!this.editor) return
    if (this.open()) { this.editor.closeSidebar(); this.open.set(false) }
    else             { this.editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID); this.open.set(true) }
  }
}
