// apps/site/src/examples/svelte/FileDrop.svelte
<script lang="ts">
  import type { WidgetProps } from '@xenolithengine/graph-svelte/components'
  let { value, setValue }: WidgetProps = $props()
  const src = $derived(typeof value === 'string' && value.startsWith('data:') ? value : '')

  function onFile(file?: File): void {
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => setValue(reader.result as string)
    reader.readAsDataURL(file)
  }
</script>

<div
  style="width:100%;height:100%;border-radius:8px;overflow:hidden;background:rgba(0,0,0,0.25);border:1px dashed var(--xeno-border);display:flex;align-items:center;justify-content:center;"
  ondragover={(e) => e.preventDefault()}
  ondrop={(e) => { e.preventDefault(); onFile(e.dataTransfer?.files?.[0]) }}
>
  {#if src}
    <img src={src} alt="" style="width:100%;height:100%;object-fit:contain;display:block;" />
  {:else}
    <label style="color:var(--xeno-muted);font-size:12px;cursor:pointer;">
      Drop image or <span style="color:var(--xeno-accent);">browse</span>
      <input type="file" accept="image/*" hidden onchange={(e) => onFile((e.target as HTMLInputElement).files?.[0])} />
    </label>
  {/if}
</div>

// apps/demo-react/src/widgets/FileDrop.tsx
import type { WidgetProps } from '@xenolithengine/graph-react'

// Drag-and-drop (or browse) an image; reads it to a data URL and previews it inline.
export function FileDrop({ value, setValue }: WidgetProps) {
  const onFile = (file?: File): void => {
    if (!file) return
    const r = new FileReader()
    r.onload = () => setValue(r.result as string)
    r.readAsDataURL(file)
  }
  const hasImg = typeof value === 'string' && value.startsWith('data:')
  return (
    <div className="w-drop" onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); onFile(e.dataTransfer.files[0]) }}>
      {hasImg
        ? <img src={value as string} className="w-drop-img" alt="" />
        : <label className="w-drop-empty">Drop image or <span>browse</span>
            <input type="file" accept="image/*" hidden onChange={(e) => onFile(e.target.files?.[0])} />
          </label>}
    </div>
  )
}
