// apps/demo-react/src/demos/CanvasWidgetDemo.tsx
import { useRef, useState } from 'react'
import { XenolithGraph, XenolithPanel } from '@xenolithengine/graph-react'
import type { XenolithEditor, NodeId } from '@xenolithengine/graph-editor'
import { buildCanvasWidget } from '@xenolithengine/demo/canvas-widget'
import { DemoStage } from '../Layout.js'

// The simplest custom widget — a click/drag level bar — lives in the framework-agnostic core
// (@xenolithengine/demo/canvas-widget): two functions, no DOM. This React file registers it via the core,
// then catches the value through onWidgetChange and shows it (and a slider that writes it back).
export function CanvasWidgetDemo() {
  const [gain, setGain] = useState(0.6)
  const editorRef = useRef<XenolithEditor | null>(null)
  const nodeIdRef = useRef<NodeId | null>(null)
  return (
    <DemoStage>
      <XenolithGraph
        className="xeno"
        resizeToWindow={false}
        onWidgetChange={(e) => { if (e.widgetId === 'gain') setGain(Number(e.value)) }}
        onReady={(editor) => {
          editorRef.current = editor
          nodeIdRef.current = buildCanvasWidget(editor).nodeId
        }}
      >
        <XenolithPanel position="top-right" style={{ width: 220 }}>
          <h3>Live value (in React)</h3>
          <p className="muted">The canvas widget commits through the editor; <code>onWidgetChange</code> hands the value back to React.</p>
          <div style={{ fontSize: 28, fontWeight: 600, color: 'var(--xeno-accent)' }}>{Math.round(gain * 100)}%</div>
          <input type="range" min={0} max={1} step={0.01} value={gain} style={{ width: '100%' }}
            onChange={(e) => editorRef.current?.setWidgetValue(nodeIdRef.current!, 'gain', e.target.valueAsNumber)} />
        </XenolithPanel>
      </XenolithGraph>
    </DemoStage>
  )
}

// apps/site/src/examples/vue/CanvasWidgetDemo.vue
<script setup lang="ts">
// Vue — a WebGL level bar. @widget-changed is the camelCase emit of widget:changed.
// The slider writes the same key back through setWidgetValue.
import { ref } from 'vue'
import { XenolithGraph, XenolithPanel } from '@xenolithengine/graph-vue'
import type { NodeId, XenolithEditor } from '@xenolithengine/graph-editor'
import { buildCanvasWidget } from '@xenolithengine/demo/canvas-widget'

const gain = ref(0.6)
const editor = ref<XenolithEditor | null>(null)
const nodeId = ref<NodeId | null>(null)

function onReady(e: XenolithEditor): void {
  editor.value = e
  nodeId.value = buildCanvasWidget(e).nodeId
}

function onWidget(payload: { widgetId: string; value: unknown }): void {
  if (payload.widgetId === 'gain') gain.value = Number(payload.value)
}

function onRange(ev: Event): void {
  const e = editor.value
  const id = nodeId.value
  if (!e || !id) return
  e.setWidgetValue(id, 'gain', (ev.target as HTMLInputElement).valueAsNumber)
}
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="onReady" @widget-changed="onWidget">
      <XenolithPanel position="top-right">
        <div style="width:220px;">
          <h3 style="margin:0 0 6px;font-size:13px;">Live value (in Vue)</h3>
          <p style="margin:0 0 8px;font-size:12px;color:var(--xeno-muted);">
            The canvas widget commits through the editor; <code>widget:changed</code> hands the value back.
          </p>
          <div style="font-size:28px;font-weight:600;color:var(--xeno-accent);">{{ Math.round(gain * 100) }}%</div>
          <input type="range" min="0" max="1" step="0.01" :value="gain" style="width:100%;" @input="onRange" />
        </div>
      </XenolithPanel>
    </XenolithGraph>
  </div>
</template>
