// apps/demo-react/src/demos/MountDemo.tsx
import { XenolithGraph } from '@xenolithengine/graph-react'
import { buildMount } from '@xenolithengine/demo/mount'
import { DemoStage } from '../Layout.js'

/** Island: the honest minimum — Xen is the default theme; load one node (mount.json) and frame it. */
export function MountDemo() {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={(editor) => buildMount(editor)} />
    </DemoStage>
  )
}

// apps/site/src/examples/vue/MountDemo.vue
<script setup lang="ts">
// Vue 3 SFC — the honest minimum: load one node, frame it. Xen is the default theme.
import { XenolithGraph } from '@xenolithengine/graph-vue'
import { buildMount } from '@xenolithengine/demo/mount'
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="buildMount" />
  </div>
</template>
