// apps/site/src/examples/svelte/NestedLayoutDemo.svelte
<!-- Svelte — ELK keeps the macro hierarchy; dagre flattens it. -->
<script lang="ts">
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { setupNestedLayout, runNestedLayout, type LayoutEngineId } from '@xenolithengine/demo/nested-layout'

  const panelEditor = createXenolithEditorContext()
  let editor = $state<XenolithEditor | null>(null)
  let engine = $state<LayoutEngineId>('elk')
  let busy = $state(false)

  async function arrange(next: LayoutEngineId = engine): Promise<void> {
    if (!editor || busy) return
    busy = true
    try { await runNestedLayout(editor, next) } finally { busy = false }
  }
  async function flip(next: LayoutEngineId): Promise<void> {
    engine = next
    await arrange(next)
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { editor = e.detail; panelEditor.set(e.detail); setupNestedLayout(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <div style="display:flex;gap:6px;">
    <XenolithButton active disabled={busy} onclick={() => arrange()}>{busy ? 'Arranging…' : 'Auto-arrange'}</XenolithButton>
    <XenolithButton active={engine === 'elk'} disabled={busy} onclick={() => flip('elk')}>ELK</XenolithButton>
    <XenolithButton active={engine === 'dagre'} disabled={busy} onclick={() => flip('dagre')}>dagre</XenolithButton>
  </div>
</XenolithPanel>

// apps/site/src/examples/vue/NestedLayoutDemo.vue
<script setup lang="ts">
// Vue — ELK keeps the macro hierarchy; dagre flattens it. runNestedLayout picks the engine.
import { ref } from 'vue'
import { XenolithGraph, XenolithPanel, XenolithButton } from '@xenolithengine/graph-vue'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupNestedLayout, runNestedLayout, type LayoutEngineId } from '@xenolithengine/demo/nested-layout'

const editor = ref<XenolithEditor | null>(null)
const engine = ref<LayoutEngineId>('elk')
const busy = ref(false)

function onReady(e: XenolithEditor): void {
  editor.value = e
  setupNestedLayout(e)
}

async function arrange(next: LayoutEngineId = engine.value): Promise<void> {
  const e = editor.value
  if (!e || busy.value) return
  busy.value = true
  try { await runNestedLayout(e, next) } finally { busy.value = false }
}

async function flip(next: LayoutEngineId): Promise<void> {
  engine.value = next
  await arrange(next)
}
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="onReady">
      <XenolithPanel position="top-left">
        <div style="display:flex;gap:6px;">
          <XenolithButton :active="true" :disabled="busy" @click="arrange()">
            {{ busy ? 'Arranging…' : 'Auto-arrange' }}
          </XenolithButton>
          <XenolithButton :active="engine === 'elk'" :disabled="busy" @click="flip('elk')">ELK</XenolithButton>
          <XenolithButton :active="engine === 'dagre'" :disabled="busy" @click="flip('dagre')">dagre</XenolithButton>
        </div>
      </XenolithPanel>
    </XenolithGraph>
  </div>
</template>
