// apps/site/src/examples/svelte/PropertiesSidebarDemo.svelte
<!-- Svelte 5 — properties sidebar: auto-open after mount, toggle is a direct editor call. -->
<script lang="ts">
  import { xenolith } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { setupPropertiesSidebar, PROPERTIES_SIDEBAR_NODE_ID } from '@xenolithengine/demo/properties-sidebar'

  let editor = $state<XenolithEditor | null>(null)
  let open = $state(true)
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  on:ready={(e) => { editor = e.detail; setupPropertiesSidebar(e.detail); e.detail.openSidebar(PROPERTIES_SIDEBAR_NODE_ID) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <XenolithButton active={open} onclick={() => {
    if (!editor) return
    if (open) { editor.closeSidebar(); open = false } else { editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID); open = true }
  }}>
    {open ? 'Close sidebar' : 'Open sidebar'}
  </XenolithButton>
</XenolithPanel>

// apps/site/src/examples/vue/PropertiesSidebarDemo.vue
<script setup lang="ts">
// Vue SFC — properties sidebar. One-time auto-open via `@ready`; toggle panel is a child component
// that uses `useEditor()` for the imperative open/close calls.
import { XenolithGraph } from '@xenolithengine/graph-vue'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupPropertiesSidebar, PROPERTIES_SIDEBAR_NODE_ID } from '@xenolithengine/demo/properties-sidebar'
import SidebarTogglePanel from './SidebarTogglePanel.vue'

function onReady(editor: XenolithEditor): void {
  setupPropertiesSidebar(editor)
  editor.openSidebar(PROPERTIES_SIDEBAR_NODE_ID)
}
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="onReady">
      <SidebarTogglePanel />
    </XenolithGraph>
  </div>
</template>
