// apps/site/src/examples/angular/NestedLayoutDemo.component.ts
// Angular — ELK keeps the macro hierarchy; dagre flattens it.
import { AfterViewInit, Component, ElementRef, OnDestroy, inject, signal, viewChild } from '@angular/core'
import { XenolithGraphService } from '@xenolithengine/graph-angular'
import { setupNestedLayout, runNestedLayout, type LayoutEngineId } from '@xenolithengine/demo/nested-layout'

@Component({
  selector: 'nested-layout-demo',
  standalone: true,
  providers: [XenolithGraphService],
  template: `
    <div style="position:absolute;inset:0;">
      <div #host class="xeno" style="position:absolute;inset:0;"></div>
      <div class="card">
        <button type="button" class="btn on" [disabled]="busy()" (click)="arrange()">
          {{ busy() ? 'Arranging…' : 'Auto-arrange' }}
        </button>
        <button type="button" class="btn" [class.on]="engine() === 'elk'" [disabled]="busy()" (click)="flip('elk')">ELK</button>
        <button type="button" class="btn" [class.on]="engine() === 'dagre'" [disabled]="busy()" (click)="flip('dagre')">dagre</button>
      </div>
    </div>
  `,
  styles: [`
    .card { position:absolute; top:12px; left:12px; z-index:5; display:flex; gap:6px; padding:6px;
      background:var(--xeno-panel,#1d1d1d); border:1px solid var(--xeno-border,#333);
      border-radius:10px; font:13px system-ui,sans-serif; }
    .btn { font:inherit; font-size:12px; padding:6px 12px; cursor:pointer; border-radius:6px;
      border:1px solid var(--xeno-border,#333); background:var(--xeno-panel,#1d1d1d);
      color:var(--xeno-text,#cfcfcf); }
    .btn.on { border-color:var(--xeno-accent,#FCB400); background:var(--xeno-accent,#FCB400);
      color:var(--xeno-canvas,#111); }
    .btn:disabled { opacity:0.4; cursor:default; }
  `],
})
export class NestedLayoutDemoComponent implements AfterViewInit, OnDestroy {
  private graph = inject(XenolithGraphService)
  private host = viewChild.required<ElementRef<HTMLDivElement>>('host')
  engine = signal<LayoutEngineId>('elk')
  busy = signal(false)

  async ngAfterViewInit(): Promise<void> {
    const editor = await this.graph.mount(this.host().nativeElement, { resizeToWindow: false })
    setupNestedLayout(editor)
  }

  async arrange(next: LayoutEngineId = this.engine()): Promise<void> {
    const editor = this.graph.editor
    if (!editor || this.busy()) return
    this.busy.set(true)
    try { await runNestedLayout(editor, next) } finally { this.busy.set(false) }
  }

  async flip(next: LayoutEngineId): Promise<void> {
    this.engine.set(next)
    await this.arrange(next)
  }

  ngOnDestroy(): void { this.graph.destroy() }
}

// apps/site/src/examples/solid/NestedLayoutDemo.tsx
// Solid — ELK keeps the macro hierarchy; dagre flattens it.
import { createSignal } from 'solid-js'
import { xenolith } from '@xenolithengine/graph-solid'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupNestedLayout, runNestedLayout, type LayoutEngineId } from '@xenolithengine/demo/nested-layout'

function btn(on: boolean, disabled: boolean): string {
  return `font:inherit;font-size:12px;padding:6px 12px;border-radius:6px;cursor:${disabled ? 'default' : 'pointer'};opacity:${disabled ? 0.4 : 1};border:1px solid ${on ? 'var(--xeno-accent)' : 'var(--xeno-border)'};background:${on ? 'var(--xeno-accent)' : 'var(--xeno-panel)'};color:${on ? 'var(--xeno-canvas)' : 'var(--xeno-text)'};`
}

export function NestedLayoutDemo() {
  const [editor, setEditor] = createSignal<XenolithEditor | null>(null)
  const [engine, setEngine] = createSignal<LayoutEngineId>('elk')
  const [busy, setBusy] = createSignal(false)

  async function arrange(next: LayoutEngineId = engine()): Promise<void> {
    const e = editor()
    if (!e || busy()) return
    setBusy(true)
    try { await runNestedLayout(e, next) } finally { setBusy(false) }
  }
  async function flip(next: LayoutEngineId): Promise<void> {
    setEngine(next)
    await arrange(next)
  }

  return (
    <div
      use:xenolith={{ resizeToWindow: false }}
      on:ready={(e) => { setEditor(e.detail); setupNestedLayout(e.detail) }}
      style="position:absolute;inset:0"
    >
      <div style="position:absolute;top:12px;left:12px;z-index:5;display:flex;gap:6px;padding:6px;background:var(--xeno-panel);border:1px solid var(--xeno-border);border-radius:10px;">
        <button type="button" style={btn(true, busy())} disabled={busy()} onClick={() => void arrange()}>{busy() ? 'Arranging…' : 'Auto-arrange'}</button>
        <button type="button" style={btn(engine() === 'elk', busy())} disabled={busy()} onClick={() => void flip('elk')}>ELK</button>
        <button type="button" style={btn(engine() === 'dagre', busy())} disabled={busy()} onClick={() => void flip('dagre')}>dagre</button>
      </div>
    </div>
  )
}
