// apps/site/src/examples/svelte/SaveRestoreDemo.svelte
<!-- Svelte 5 — save & restore: autosave rides the store bag's graphJSON (commit-time
     snapshots), download/upload/restore through the shared helpers; the panel is the real
     XenolithPanel portalled into the editor overlay. -->
<script lang="ts">
  import { xenolith, createXenolithStores } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import {
    initSaveRestore, downloadGraph, uploadGraph, saveToLocal, restoreFromLocal, hasSaved,
  } from '@xenolithengine/demo/save-restore'

  const stores = createXenolithStores()
  const graphJSON = stores.graphJSON // destructure for the $-auto-subscription
  let editor = $state<XenolithEditor | null>(null)
  let savedAt = $state<number | null>(null)
  let fileInput: HTMLInputElement
  let timer: ReturnType<typeof setTimeout> | null = null
  let first = true
  const hasSave = hasSaved()

  // Commit-time autosave: every committed change produces a fresh graphJSON snapshot.
  $effect(() => {
    const json = $graphJSON // tracked — the effect re-runs on every commit
    if (!editor || !json || first) { first = false; return }
    if (timer) clearTimeout(timer)
    const e = editor
    timer = setTimeout(() => { saveToLocal(e); savedAt = Date.now() }, 500)
  })
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  on:ready={(e) => { editor = e.detail; stores.editor.set(e.detail); initSaveRestore(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <XenolithButton onclick={() => editor && downloadGraph(editor)}>↓ Download .json</XenolithButton>
  <XenolithButton onclick={() => fileInput.click()}>↑ Upload .json</XenolithButton>
  <XenolithButton disabled={savedAt === null && !hasSave} onclick={() => editor && restoreFromLocal(editor)}>↺ Restore last</XenolithButton>
  <span>{savedAt ? '✓ Autosaved to your browser' : 'Edit the graph — it autosaves to localStorage.'}</span>
  <input bind:this={fileInput} type="file" accept="application/json,.json" hidden
    onchange={(ev) => { const f = (ev.currentTarget as HTMLInputElement).files?.[0]; if (f && editor) uploadGraph(editor, f) }} />
</XenolithPanel>

// apps/site/src/examples/solid/SaveRestoreDemo.tsx
// Solid — save & restore: autosave rides the store bag's graphJSON accessor (commit-time
// snapshots) via createEffect; imperative IO through the shared helpers.
import { createEffect, createSignal } from 'solid-js'
import { xenolith, createXenolithStores } from '@xenolithengine/graph-solid'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import {
  initSaveRestore, downloadGraph, uploadGraph, saveToLocal, restoreFromLocal, hasSaved,
} from '@xenolithengine/demo/save-restore'

export function SaveRestoreDemo() {
  const stores = createXenolithStores()
  const [editor, setEditor] = createSignal<XenolithEditor | null>(null)
  const [savedAt, setSavedAt] = createSignal<number | null>(null)
  const [hasSave] = createSignal(hasSaved())
  let timer: ReturnType<typeof setTimeout> | null = null
  let first = true
  let fileInput: HTMLInputElement | undefined

  // Commit-time autosave: every committed change produces a fresh graphJSON snapshot.
  createEffect(() => {
    const json = stores.graphJSON() // tracked signal read
    const e = editor()
    if (!e || !json || first) { first = false; return }
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => { saveToLocal(e); setSavedAt(Date.now()) }, 500)
  })

  const btn = 'width:100%;padding:6px 10px;font-size:12px;cursor:pointer;border:1px solid var(--xeno-border);border-radius:6px;background:transparent;color:var(--xeno-text)'

  return (
    <div
      use:xenolith={{ resizeToWindow: false }}
      on:ready={(e) => { setEditor(e.detail); stores.setEditor(e.detail); initSaveRestore(e.detail) }}
      style="position:absolute;inset:0"
    >
      <div style="position:absolute;top:12px;left:12px;display:flex;flex-direction:column;gap:6px;width:180px;padding:10px;background:var(--xeno-panel);border:1px solid var(--xeno-border);border-radius:8px;font:12px Inter,system-ui,sans-serif;color:var(--xeno-text);z-index:5">
        <button style={btn} onClick={() => { const e = editor(); if (e) downloadGraph(e) }}>↓ Download .json</button>
        <button style={btn} onClick={() => fileInput?.click()}>↑ Upload .json</button>
        <button style={btn} disabled={savedAt() === null && !hasSave()} onClick={() => { const e = editor(); if (e) restoreFromLocal(e) }}>↺ Restore last</button>
        <span style="color:#9a9a9a;font-size:11px">{savedAt() ? '✓ Autosaved to your browser' : 'Edit the graph — it autosaves.'}</span>
        <input ref={fileInput} type="file" accept="application/json,.json" hidden
          onChange={(ev) => { const f = ev.currentTarget.files?.[0]; const e = editor(); if (f && e) uploadGraph(e, f) }} />
      </div>
    </div>
  )
}
