// apps/site/src/examples/angular/SaveRestoreDemo.component.ts
// Angular standalone component — save & restore. Imperative IO via the shared helpers; autosave
// rides the `(historyChanged)` Output. Editor reference is captured from `(ready)` once.
import { Component, signal, ViewChild, ElementRef } from '@angular/core'
import { XenolithGraphComponent } from '@xenolithengine/angular'
import type { XenolithEditor } from '@xenolithengine/editor'
import {
  initSaveRestore, downloadGraph, uploadGraph, saveToLocal, restoreFromLocal, hasSaved,
} from '@xenolithengine/demo/save-restore'

@Component({
  selector: 'save-restore-demo',
  standalone: true,
  imports: [XenolithGraphComponent],
  template: `
    <div class="app" style="position:absolute;inset:0;">
      <xenolith-graph
        class="xeno"
        [resizeToWindow]="false"
        (ready)="onReady($event)"
        (historyChanged)="scheduleAutosave()">
      </xenolith-graph>

      <div data-xeno-panel class="panel">
        <p class="label">Save / restore</p>
        <button class="btn" (click)="download()">↓ Download .json</button>
        <button class="btn" (click)="fileInput.click()">↑ Upload .json</button>
        <button class="btn" [disabled]="savedAt() === null && !hasSaved" (click)="restore()">↺ Restore last</button>
        <span class="status">{{ savedAt() ? '✓ Autosaved to your browser' : 'Edit the graph — it autosaves to localStorage.' }}</span>
        <input #fileInput type="file" accept="application/json,.json" hidden (change)="onUpload($event)" />
      </div>
    </div>
  `,
  styles: [\`
    .panel { position:absolute; top:12px; left:12px; display:flex; flex-direction:column; gap:6px;
      width:180px; padding:10px; background:var(--xeno-panel,#1d1d1d);
      border:1px solid var(--xeno-border,#333); border-radius:8px;
      font:12px Inter,system-ui,sans-serif; color:var(--xeno-text,#cfcfcf); z-index:5; }
    .label { margin:0; font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:#9a9a9a; }
    .btn { width:100%; padding:6px 10px; font-size:12px; cursor:pointer;
      border:1px solid var(--xeno-border,#333); border-radius:6px;
      background:transparent; color:var(--xeno-text,#cfcfcf); }
    .status { color:#9a9a9a; font-size:11px; line-height:1.4; }
  \`],
})
export class SaveRestoreDemoComponent {
  private editor: XenolithEditor | null = null
  private timer: ReturnType<typeof setTimeout> | null = null
  private first = true
  savedAt = signal<number | null>(null)
  readonly hasSaved = hasSaved()

  onReady(editor: XenolithEditor): void {
    this.editor = editor
    initSaveRestore(editor)
  }

  scheduleAutosave(): void {
    if (this.first) { this.first = false; return }
    if (!this.editor) return
    if (this.timer) clearTimeout(this.timer)
    const e = this.editor
    this.timer = setTimeout(() => { saveToLocal(e); this.savedAt.set(Date.now()) }, 500)
  }

  download(): void { if (this.editor) downloadGraph(this.editor) }
  restore(): void { if (this.editor) restoreFromLocal(this.editor) }
  onUpload(ev: Event): void {
    const f = (ev.target as HTMLInputElement).files?.[0]
    if (f && this.editor) uploadGraph(this.editor, f)
  }
}

// apps/site/src/examples/solid/SaveRestoreDemo.tsx
// Solid — save & restore: autosave rides the store bag's graphJSON accessor (commit-time
// snapshots) via createEffect; imperative IO through the shared helpers.
import { createEffect, createSignal } from 'solid-js'
import { xenolith, createXenolithStores } from '@xenolithengine/graph-solid'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import {
  initSaveRestore, downloadGraph, uploadGraph, saveToLocal, restoreFromLocal, hasSaved,
} from '@xenolithengine/demo/save-restore'

export function SaveRestoreDemo() {
  const stores = createXenolithStores()
  const [editor, setEditor] = createSignal<XenolithEditor | null>(null)
  const [savedAt, setSavedAt] = createSignal<number | null>(null)
  const [hasSave] = createSignal(hasSaved())
  let timer: ReturnType<typeof setTimeout> | null = null
  let first = true
  let fileInput: HTMLInputElement | undefined

  // Commit-time autosave: every committed change produces a fresh graphJSON snapshot.
  createEffect(() => {
    const json = stores.graphJSON() // tracked signal read
    const e = editor()
    if (!e || !json || first) { first = false; return }
    if (timer) clearTimeout(timer)
    timer = setTimeout(() => { saveToLocal(e); setSavedAt(Date.now()) }, 500)
  })

  const btn = 'width:100%;padding:6px 10px;font-size:12px;cursor:pointer;border:1px solid var(--xeno-border);border-radius:6px;background:transparent;color:var(--xeno-text)'

  return (
    <div
      use:xenolith={{ resizeToWindow: false }}
      on:ready={(e) => { setEditor(e.detail); stores.setEditor(e.detail); initSaveRestore(e.detail) }}
      style="position:absolute;inset:0"
    >
      <div style="position:absolute;top:12px;left:12px;display:flex;flex-direction:column;gap:6px;width:180px;padding:10px;background:var(--xeno-panel);border:1px solid var(--xeno-border);border-radius:8px;font:12px Inter,system-ui,sans-serif;color:var(--xeno-text);z-index:5">
        <button style={btn} onClick={() => { const e = editor(); if (e) downloadGraph(e) }}>↓ Download .json</button>
        <button style={btn} onClick={() => fileInput?.click()}>↑ Upload .json</button>
        <button style={btn} disabled={savedAt() === null && !hasSave()} onClick={() => { const e = editor(); if (e) restoreFromLocal(e) }}>↺ Restore last</button>
        <span style="color:#9a9a9a;font-size:11px">{savedAt() ? '✓ Autosaved to your browser' : 'Edit the graph — it autosaves.'}</span>
        <input ref={fileInput} type="file" accept="application/json,.json" hidden
          onChange={(ev) => { const f = ev.currentTarget.files?.[0]; const e = editor(); if (f && e) uploadGraph(e, f) }} />
      </div>
    </div>
  )
}
