// apps/site/src/examples/svelte/EventsDemo.svelte
<!-- Svelte 5 — typed event callbacks + the store bag: selection via the bag's selection store,
     the live log through the action's on:* CustomEvents (payloads in e.detail). -->
<script lang="ts">
  import { xenolith, createXenolithStores } from '@xenolithengine/graph-svelte'
  import { XenolithPanel } from '@xenolithengine/graph-svelte/components'
  import { loadDemo } from '@xenolithengine/demo/scene'

  const stores = createXenolithStores()
  const selection = stores.selection // destructure for the $-auto-subscription in the template
  let log = $state<string[]>([])

  const push = (line: string): void => { log = [line, ...log].slice(0, 40) }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  on:ready={(e) => { stores.editor.set(e.detail); loadDemo(e.detail) }}
  on:node:click={(e) => push(`node:click ${String(e.detail.nodeId)}`)}
  on:selection:changed={(e) => push(`selection:changed (${e.detail.nodeIds.length})`)}
  on:edge:connected={(e) => push(`edge:connected ${String(e.detail.edge.id)}`)}
  on:widget:changed={(e) => push(`widget:changed ${e.detail.widgetId} = ${JSON.stringify(e.detail.value)}`)}
  on:history:changed={(e) => push(`history undo=${e.detail.canUndo} redo=${e.detail.canRedo}`)}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-right">
  <h3>Selection</h3>
  {#each $selection as id (id)}<div>{id}</div>{/each}
  <h3>Event log</h3>
  {#each log as line}<div>{line}</div>{/each}
</XenolithPanel>

// apps/demo-react/src/demos/EventsDemo.tsx
import { useState } from 'react'
import { XenolithGraph, XenolithPanel, useEditorEvent, useSelection } from '@xenolithengine/graph-react'
import { DemoStage } from '../Layout.js'
import { loadDemo } from '../demo-data.js'

const SIDE_PANEL = { width: 280, maxHeight: 'calc(100% - 24px)', overflowY: 'auto' as const }

/** Island: typed event callbacks wired to React state — a live log + selection inspector, all in an
 *  in-editor panel.
 *
 *  Canon: subscriptions live with the state that records them. EventsPanel uses `useEditorEvent`
 *  (one line per event, auto-rebinds on editor swap); `useSelection()` replaces the manual
 *  selection-tracking state. No on* callback props on <XenolithGraph>. */
function EventsPanel() {
  const selected = useSelection()
  const [log, setLog] = useState<string[]>([])
  const [widgets, setWidgets] = useState<Record<string, unknown>>({})
  const push = (line: string): void => setLog((l) => [line, ...l].slice(0, 40))

  useEditorEvent('node:click', (e) => push(`node:click ${e.nodeId}`))
  useEditorEvent('selection:changed', (e) => push(`selection:changed (${e.nodeIds.length})`))
  useEditorEvent('node:moved', (e) => push(`node:moved ${e.nodeId} → ${Math.round(e.position.x)},${Math.round(e.position.y)}`))
  useEditorEvent('edge:connected', (e) => push(`edge:connected ${e.edge.id}`))
  useEditorEvent('edge:disconnected', (e) => push(`edge:disconnected ${e.edgeId}`))
  useEditorEvent('widget:changed', (e) => {
    setWidgets((w) => ({ ...w, [`${e.nodeId}.${e.widgetId}`]: e.value }))
    push(`widget:changed ${e.widgetId} = ${JSON.stringify(e.value)}`)
  })
  useEditorEvent('history:changed', (e) => push(`history undo=${e.canUndo} redo=${e.canRedo}`))

  return (
    <XenolithPanel position="top-right" style={SIDE_PANEL}>
      <h3>Selection</h3>
      {selected.length === 0 ? <p className="muted">Nothing selected.</p> : selected.map((id) => (
        <div className="row" key={String(id)}><span>{String(id)}</span></div>
      ))}
      <h3 style={{ marginTop: 16 }}>Widget values</h3>
      {Object.keys(widgets).length === 0
        ? <p className="muted">Drag a slider, type in a field, toggle a switch…</p>
        : Object.entries(widgets).map(([id, v]) => (
          <div className="row" key={id}><span className="muted">{id}</span><span>{JSON.stringify(v)}</span></div>
        ))}
      <h3 style={{ marginTop: 16 }}>Event log</h3>
      <div className="log">
        {log.length === 0 && <p className="muted">Interact with the graph…</p>}
        {log.map((line, i) => <div key={i}>{line}</div>)}
      </div>
    </XenolithPanel>
  )
}

export function EventsDemo() {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={loadDemo}>
        <EventsPanel />
      </XenolithGraph>
    </DemoStage>
  )
}
