// apps/site/src/examples/svelte/ExportImageDemo.svelte
<!-- Svelte — full-graph image export. The editor from onready is enough; the download
     helper is framework-agnostic. -->
<script lang="ts">
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton, XenolithControls } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { loadDemo } from '@xenolithengine/demo/scene'
  import { exportGraphImage } from '@xenolithengine/demo/export-image'

  const panelEditor = createXenolithEditorContext()
  let editor = $state<XenolithEditor | null>(null)
  let busy = $state(false)

  async function save(format: 'png' | 'jpeg', scale: number): Promise<void> {
    if (!editor || busy) return
    busy = true
    try { await exportGraphImage(editor, format, scale) } finally { busy = false }
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { editor = e.detail; panelEditor.set(e.detail); loadDemo(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithControls position="bottom-left" />

<XenolithPanel position="top-left">
  <div style="display:flex;flex-direction:column;gap:6px;width:190px;">
    <p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--xeno-muted);">Export image</p>
    <XenolithButton style="width:100%" disabled={busy} onclick={() => save('png', 1)}>↓ PNG · 1×</XenolithButton>
    <XenolithButton style="width:100%" disabled={busy} onclick={() => save('png', 2)}>↓ PNG · 2× (retina)</XenolithButton>
    <XenolithButton style="width:100%" disabled={busy} onclick={() => save('jpeg', 2)}>↓ JPG · 2×</XenolithButton>
    <span style="color:var(--xeno-muted);font-size:11px;line-height:1.45;">
      Exports the entire graph, not just what’s on screen.
    </span>
  </div>
</XenolithPanel>

// apps/demo-react/src/demos/ExportImageDemo.tsx
import { useState } from 'react'
import { XenolithGraph, XenolithPanel, XenolithButton, XenolithControls, useEditor } from '@xenolithengine/react'
import { loadDemo } from '@xenolithengine/demo/scene'
import { exportGraphImage } from '@xenolithengine/demo/export-image'
import { DemoStage } from '../Layout.js'

// Showcase: render the whole graph to an image. The export + download logic lives in the
// framework-agnostic core (@xenolithengine/demo/export-image); this React file is just the button panel.

function ExportPanel(): React.ReactElement {
  const editor = useEditor()
  const [busy, setBusy] = useState(false)
  const exportAs = async (format: 'png' | 'jpeg', scale: number): Promise<void> => {
    if (busy) return
    setBusy(true)
    try { await exportGraphImage(editor, format, scale) } finally { setBusy(false) }
  }
  const full = { width: '100%' }
  return (
    <XenolithPanel position="top-left" style={{ display: 'flex', flexDirection: 'column', gap: 6, width: 190 }}>
      <p style={{ margin: 0, fontSize: 11, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--xeno-muted)' }}>Export image</p>
      <XenolithButton style={full} disabled={busy} onClick={() => void exportAs('png', 1)}>↓ PNG · 1×</XenolithButton>
      <XenolithButton style={full} disabled={busy} onClick={() => void exportAs('png', 2)}>↓ PNG · 2× (retina)</XenolithButton>
      <XenolithButton style={full} disabled={busy} onClick={() => void exportAs('jpeg', 2)}>↓ JPG · 2×</XenolithButton>
      <span style={{ color: 'var(--xeno-muted)', fontSize: 11, lineHeight: 1.45 }}>
        Exports the entire graph, not just what’s on screen.
      </span>
    </XenolithPanel>
  )
}

/** Showcase: full-graph image export at any scale. */
export function ExportImageDemo(): React.ReactElement {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={loadDemo}>
        <XenolithControls position="bottom-left" />
        <ExportPanel />
      </XenolithGraph>
    </DemoStage>
  )
}
