// apps/site/src/examples/vue/LoadDemo.vue
<script setup lang="ts">
// Vue — load a saved xenolith.v1 graph on ready, reload it from the panel.
// The editor arrives on @ready (the payload is the instance, not a DOM event).
import { ref } from 'vue'
import { XenolithGraph, XenolithControls, XenolithPanel, XenolithButton } from '@xenolithengine/graph-vue'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { loadDemo } from '@xenolithengine/demo/scene'
import { demoGraph } from '@xenolithengine/demo'

const editor = ref<XenolithEditor | null>(null)

function onReady(e: XenolithEditor): void {
  editor.value = e
  loadDemo(e)
}

function reload(): void {
  const e = editor.value
  if (!e) return
  e.loadJSON(demoGraph)
  e.view.fitView({ padding: 48, maxZoom: 1 })
}
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="onReady">
      <XenolithControls position="bottom-left" />
      <XenolithPanel position="top-right">
        <XenolithButton @click="reload">Reload graph</XenolithButton>
      </XenolithPanel>
    </XenolithGraph>
  </div>
</template>

// apps/demo-react/src/demos/LoadDemo.tsx
import { useRef } from 'react'
import { XenolithGraph, XenolithControls, XenolithPanel, XenolithButton } from '@xenolithengine/graph-react'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { DemoStage } from '../Layout.js'
import { loadDemo, demoGraph } from '../demo-data.js'

/** Island: load a real saved xenolith.v1 graph; an in-editor panel reloads it. */
export function LoadDemo() {
  const editorRef = useRef<XenolithEditor | null>(null)
  return (
    <DemoStage>
      <XenolithGraph
        className="xeno"
        resizeToWindow={false}
        onReady={(e) => { editorRef.current = e; loadDemo(e) }}
      >
        <XenolithControls position="bottom-left" />
        <XenolithPanel position="top-right">
          <XenolithButton onClick={() => { const e = editorRef.current; if (e) { e.loadJSON(demoGraph); e.fitView({ padding: 48, maxZoom: 1 }) } }}>
            Reload graph
          </XenolithButton>
        </XenolithPanel>
      </XenolithGraph>
    </DemoStage>
  )
}
