// apps/site/src/examples/svelte/StressTestDemo.svelte
<!-- Svelte — the node count is the store bag. Destructure `nodes` before `$`. -->
<script lang="ts">
  import { xenolith, createXenolithStores, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { setupStressTest, addStressNodes } from '@xenolithengine/demo/stress-test'

  const stores = createXenolithStores()
  const nodes = stores.nodes
  const panelEditor = createXenolithEditorContext()
  let editor = $state<XenolithEditor | null>(null)

  function add(n: number): void {
    if (editor) addStressNodes(editor, n)
  }
  function reset(): void {
    editor?.clear()
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false, zoomBounds: [0.05, 2] }}
  onready={(e) => { editor = e.detail; panelEditor.set(e.detail); stores.editor.set(e.detail); setupStressTest(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <div style="display:flex;flex-direction:column;gap:6px;width:168px;">
    <p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--xeno-muted);">Stress test</p>
    <div style="font-size:22px;font-weight:700;color:var(--xeno-accent);font-variant-numeric:tabular-nums;">
      {$nodes.length}<span style="font-size:12px;color:var(--xeno-muted);font-weight:400;"> nodes</span>
    </div>
    <div style="display:flex;gap:6px;">
      <XenolithButton style="flex:1" onclick={() => add(500)}>+500</XenolithButton>
      <XenolithButton style="flex:1" onclick={() => add(1000)}>+1000</XenolithButton>
    </div>
    <XenolithButton style="width:100%" onclick={() => add(5000)}>+5000</XenolithButton>
    <XenolithButton style="width:100%" onclick={() => reset()}>Reset</XenolithButton>
    <span style="color:var(--xeno-muted);font-size:11px;line-height:1.4;">
      WebGL, render-on-demand. Live stats top-right. The count is the nodes store.
    </span>
  </div>
</XenolithPanel>

// apps/demo-react/src/demos/StressTestDemo.tsx
import { XenolithGraph, XenolithPanel, XenolithButton, useEditor, useNodes } from '@xenolithengine/graph-react'
import { setupStressTest, addStressNodes } from '@xenolithengine/demo/stress-test'
import { DemoStage } from '../Layout.js'

// Perf flex: hundreds–thousands of WebGL nodes, pan/zoom at 60fps. The count is just
// `useNodes().length` — no handle, no manual setCount. Zoom floor is dropped so 10k+ nodes
// fit in view; minimap helps navigate when zoomed in.

function StressPanel() {
  const editor = useEditor()
  const nodes = useNodes()
  return (
    <XenolithPanel position="top-left" style={{ display: 'flex', flexDirection: 'column', gap: 6, width: 168 }}>
      <p style={{ margin: 0, fontSize: 11, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--xeno-muted)' }}>Stress test</p>
      <div style={{ fontSize: 22, fontWeight: 700, color: 'var(--xeno-accent)', fontVariantNumeric: 'tabular-nums' }}>
        {nodes.length}<span style={{ fontSize: 12, color: 'var(--xeno-muted)', fontWeight: 400 }}> nodes</span>
      </div>
      <div style={{ display: 'flex', gap: 6 }}>
        <XenolithButton onClick={() => addStressNodes(editor, 500)} style={{ flex: 1 }}>+500</XenolithButton>
        <XenolithButton onClick={() => addStressNodes(editor, 1000)} style={{ flex: 1 }}>+1000</XenolithButton>
      </div>
      <XenolithButton onClick={() => addStressNodes(editor, 5000)} style={{ width: '100%' }}>+5000</XenolithButton>
      <XenolithButton onClick={() => editor.clear()} style={{ width: '100%' }}>Reset</XenolithButton>
      <span style={{ color: 'var(--xeno-muted)', fontSize: 11, lineHeight: 1.4 }}>
        WebGL, render-on-demand. Live stats top-right.
      </span>
    </XenolithPanel>
  )
}

export function StressTestDemo() {
  return (
    <DemoStage>
      <XenolithGraph
        className="xeno"
        resizeToWindow={false}
        zoomBounds={[0.05, 2]}
        onReady={setupStressTest}
      >
        <StressPanel />
      </XenolithGraph>
    </DemoStage>
  )
}
