// apps/demo-react/src/demos/AudioSynthDemo.tsx
import { useEffect, useRef, useState } from 'react'
import { XenolithGraph, XenolithPanel, XenolithButton, useEditor } from '@xenolithengine/react'
import { loadAudioGraph, createAudioEngine, type AudioSynthHandle } from '@xenolithengine/demo/audio-synth'
import { DemoStage } from '../Layout.js'

// A tiny Web Audio synth built ON the graph: Oscillator → Filter → Gain → Output.
//
// Canon: the engine (an external system: AudioContext + event subscriptions) lives where it's
// used — inside the panel that drives it. `useEditor()` gives the editor directly; a ref holds
// the engine because it's imperative, not state; the effect's cleanup disposes on unmount.

function AudioPanel() {
  const editor = useEditor()
  const engineRef = useRef<AudioSynthHandle | null>(null)
  const [playing, setPlaying] = useState(false)

  useEffect(() => {
    engineRef.current = createAudioEngine(editor)
    return () => { engineRef.current?.dispose(); engineRef.current = null }
  }, [editor])

  const toggle = () => {
    const eng = engineRef.current
    if (!eng) return
    if (playing) eng.stop()
    else eng.play()
    setPlaying(!playing)
  }

  return (
    <XenolithPanel position="top-left" style={{ display: 'flex', flexDirection: 'column', gap: 6, maxWidth: 220 }}>
      <XenolithButton active={playing} onClick={toggle} style={{ width: '100%' }}>
        {playing ? '■ Stop' : '▶ Play'}
      </XenolithButton>
      <span style={{ color: 'var(--xeno-muted)', fontSize: 11, lineHeight: 1.4 }}>
        Tweak the knobs while it plays — the chain is wired from the graph; the active path glows.
      </span>
    </XenolithPanel>
  )
}

/** Showcase: a real Web Audio synth built on the node graph. */
export function AudioSynthDemo() {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={loadAudioGraph}>
        <AudioPanel />
      </XenolithGraph>
    </DemoStage>
  )
}

// apps/site/src/examples/svelte/AudioSynthDemo.svelte
<script lang="ts">
  import { onDestroy } from 'svelte'
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import { loadAudioGraph, createAudioEngine, type AudioSynthHandle } from '@xenolithengine/demo/audio-synth'

  const panelEditor = createXenolithEditorContext()
  let playing = $state(false)
  let engine: AudioSynthHandle | null = null

  function toggle(): void {
    if (!engine) return
    if (playing) engine.stop()
    else engine.play()
    playing = !playing
  }

  onDestroy(() => { engine?.dispose(); engine = null })
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { panelEditor.set(e.detail); loadAudioGraph(e.detail); engine = createAudioEngine(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <div style="display:flex;flex-direction:column;gap:6px;max-width:220px;">
    <XenolithButton active={playing} style="width:100%" onclick={toggle}>
      {playing ? '■ Stop' : '▶ Play'}
    </XenolithButton>
    <span style="color:var(--xeno-muted);font-size:11px;line-height:1.4;">
      Tweak the knobs while it plays — the chain is wired from the graph; the active path glows.
    </span>
  </div>
</XenolithPanel>
