// apps/site/src/examples/vue/AutoLayoutDemo.vue
<script setup lang="ts">
// Vue — one arrange call is one undo step. Direction is panel state passed to runAutoLayout.
import { ref } from 'vue'
import { XenolithGraph, XenolithPanel, XenolithButton } from '@xenolithengine/graph-vue'
import type { XenolithEditor } from '@xenolithengine/graph-editor'
import { setupAutoLayout, runAutoLayout } from '@xenolithengine/demo/auto-layout'

type Direction = 'LR' | 'TB'

const editor = ref<XenolithEditor | null>(null)
const dir = ref<Direction>('LR')
const busy = ref(false)

function onReady(e: XenolithEditor): void {
  editor.value = e
  setupAutoLayout(e)
}

async function arrange(next: Direction = dir.value): Promise<void> {
  const e = editor.value
  if (!e || busy.value) return
  busy.value = true
  try { await runAutoLayout(e, { direction: next }) } finally { busy.value = false }
}

async function flip(next: Direction): Promise<void> {
  dir.value = next
  await arrange(next)
}
</script>

<template>
  <div class="app" style="position:absolute;inset:0;">
    <XenolithGraph class="xeno" :resize-to-window="false" @ready="onReady">
      <XenolithPanel position="top-left">
        <div style="display:flex;gap:6px;">
          <XenolithButton :active="true" :disabled="busy" @click="arrange()">
            {{ busy ? 'Arranging…' : 'Auto-arrange' }}
          </XenolithButton>
          <XenolithButton :active="dir === 'LR'" :disabled="busy" @click="flip('LR')">LR</XenolithButton>
          <XenolithButton :active="dir === 'TB'" :disabled="busy" @click="flip('TB')">TB</XenolithButton>
        </div>
      </XenolithPanel>
    </XenolithGraph>
  </div>
</template>

// apps/site/src/examples/svelte/AutoLayoutDemo.svelte
<!-- Svelte — one arrange call is one undo step. Direction is component state. -->
<script lang="ts">
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { setupAutoLayout, runAutoLayout } from '@xenolithengine/demo/auto-layout'

  type Direction = 'LR' | 'TB'

  const panelEditor = createXenolithEditorContext()
  let editor = $state<XenolithEditor | null>(null)
  let dir = $state<Direction>('LR')
  let busy = $state(false)

  async function arrange(next: Direction = dir): Promise<void> {
    if (!editor || busy) return
    busy = true
    try { await runAutoLayout(editor, { direction: next }) } finally { busy = false }
  }
  async function flip(next: Direction): Promise<void> {
    dir = next
    await arrange(next)
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { editor = e.detail; panelEditor.set(e.detail); setupAutoLayout(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-left">
  <div style="display:flex;gap:6px;">
    <XenolithButton active disabled={busy} onclick={() => arrange()}>{busy ? 'Arranging…' : 'Auto-arrange'}</XenolithButton>
    <XenolithButton active={dir === 'LR'} disabled={busy} onclick={() => flip('LR')}>LR</XenolithButton>
    <XenolithButton active={dir === 'TB'} disabled={busy} onclick={() => flip('TB')}>TB</XenolithButton>
  </div>
</XenolithPanel>
