// apps/site/src/examples/solid/CanvasWidgetDemo.tsx
// Solid — a WebGL level bar. widget:changed is subscribed from on:ready. The directive's
// attribute form is on:widget-changed (one colon); on:widget:changed fails Vite's dep scan.
import { createSignal } from 'solid-js'
import { xenolith } from '@xenolithengine/graph-solid'
import type { NodeId, XenolithEditor } from '@xenolithengine/graph-editor'
import { buildCanvasWidget } from '@xenolithengine/demo/canvas-widget'

export function CanvasWidgetDemo() {
  const [gain, setGain] = createSignal(0.6)
  const [editor, setEditor] = createSignal<XenolithEditor | null>(null)
  const [nodeId, setNodeId] = createSignal<NodeId | null>(null)

  return (
    <div
      use:xenolith={{ resizeToWindow: false }}
      on:ready={(e) => {
        setEditor(e.detail)
        setNodeId(buildCanvasWidget(e.detail).nodeId)
        e.detail.on('widget:changed', (payload) => {
          if (payload.widgetId === 'gain') setGain(Number(payload.value))
        })
      }}
      style="position:absolute;inset:0"
    >
      <div style="position:absolute;top:12px;right:12px;z-index:5;width:220px;padding:10px;background:var(--xeno-panel);border:1px solid var(--xeno-border);border-radius:10px;color:var(--xeno-text);font:13px system-ui,sans-serif;">
        <h3 style="margin:0 0 6px;font-size:13px;">Live value (in Solid)</h3>
        <p style="margin:0 0 8px;font-size:12px;color:var(--xeno-muted);">
          The canvas widget commits through the editor; widget:changed hands the value back.
        </p>
        <div style="font-size:28px;font-weight:600;color:var(--xeno-accent);">{Math.round(gain() * 100)}%</div>
        <input
          type="range"
          min="0"
          max="1"
          step="0.01"
          value={gain()}
          style="width:100%;"
          onInput={(ev) => {
            const live = editor()
            const id = nodeId()
            if (!live || !id) return
            live.setWidgetValue(id, 'gain', (ev.currentTarget as HTMLInputElement).valueAsNumber)
          }}
        />
      </div>
    </div>
  )
}

// apps/site/src/examples/svelte/CanvasWidgetDemo.svelte
<!-- Svelte — a WebGL level bar. widget:changed is subscribed on the editor from onready.
     The range uses oninput, so the file stays on the Svelte 5 event form (no on:ready mix). -->
<script lang="ts">
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel } from '@xenolithengine/graph-svelte/components'
  import type { NodeId, XenolithEditor } from '@xenolithengine/graph-editor'
  import { buildCanvasWidget } from '@xenolithengine/demo/canvas-widget'

  const panelEditor = createXenolithEditorContext()
  let gain = $state(0.6)
  let editor = $state<XenolithEditor | null>(null)
  let nodeId = $state<NodeId | null>(null)

  function onRange(ev: Event): void {
    if (!editor || !nodeId) return
    editor.setWidgetValue(nodeId, 'gain', (ev.target as HTMLInputElement).valueAsNumber)
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => {
    editor = e.detail
    panelEditor.set(e.detail)
    nodeId = buildCanvasWidget(e.detail).nodeId
    e.detail.on('widget:changed', (payload) => {
      if (payload.widgetId === 'gain') gain = Number(payload.value)
    })
  }}
  style="position:absolute;inset:0"
></div>

<XenolithPanel position="top-right">
  <div style="width:220px;">
    <h3 style="margin:0 0 6px;font-size:13px;">Live value (in Svelte)</h3>
    <p style="margin:0 0 8px;font-size:12px;color:var(--xeno-muted);">
      The canvas widget commits through the editor; <code>widget:changed</code> hands the value back.
    </p>
    <div style="font-size:28px;font-weight:600;color:var(--xeno-accent);">{Math.round(gain * 100)}%</div>
    <input type="range" min="0" max="1" step="0.01" value={gain} style="width:100%;" oninput={onRange} />
  </div>
</XenolithPanel>
