// apps/demo-react/src/demos/ConnectionValidationDemo.tsx
import { useState } from 'react'
import { XenolithGraph, XenolithPanel, XenolithControls } from '@xenolithengine/graph-react'
import { buildConnectionValidation, type Attempt } from '@xenolithengine/demo/connection-validation'
import { DemoStage } from '../Layout.js'

// Showcase: typed-pin validation + a custom cycle-prevention guard. The graph + the guard live in the
// framework-agnostic core (@xenolithengine/demo/connection-validation); this React file just renders the
// live attempt log fed by the core's `log` callback.

function RulesPanel({ log }: { log: Attempt[] }): React.ReactElement {
  return (
    <XenolithPanel position="top-right" style={{ display: 'flex', flexDirection: 'column', gap: 8, width: 230 }}>
      <p style={{ margin: 0, fontSize: 11, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--xeno-muted)' }}>Connection rules</p>
      <span style={{ color: 'var(--xeno-muted)', fontSize: 11, lineHeight: 1.5 }}>
        Pins are typed. Drag <b style={{ color: 'var(--xeno-text)' }}>Text</b> → a float input — refused (snaps back).
        Drag <b style={{ color: 'var(--xeno-text)' }}>C</b> → <b style={{ color: 'var(--xeno-text)' }}>A</b> — blocked (cycle).
      </span>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 3, maxHeight: 168, overflow: 'hidden' }}>
        {log.length === 0 && <span style={{ color: 'var(--xeno-muted)', fontSize: 11 }}>No attempts yet.</span>}
        {log.map((a, i) => (
          <span key={i} style={{ fontSize: 11, fontFamily: 'var(--xeno-mono, monospace)', color: a.ok ? '#39d98a' : '#ff5b6e' }}>
            {a.ok ? '✓' : '✗'} {a.text}
          </span>
        ))}
      </div>
    </XenolithPanel>
  )
}

/** Showcase: typed-pin validation + custom cycle-prevention guard. */
export function ConnectionValidationDemo(): React.ReactElement {
  const [log, setLog] = useState<Attempt[]>([])
  const push = (a: Attempt): void => setLog((l) => [a, ...l].slice(0, 8))
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={(editor) => buildConnectionValidation(editor, push)}>
        <XenolithControls position="bottom-left" />
        <RulesPanel log={log} />
      </XenolithGraph>
    </DemoStage>
  )
}

// apps/site/src/examples/svelte/ConnectionValidationDemo.svelte
<!-- Svelte — the attempt log is local state. The guard and the graph are shared. -->
<script lang="ts">
  import { xenolith, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithControls } from '@xenolithengine/graph-svelte/components'
  import { buildConnectionValidation, type Attempt } from '@xenolithengine/demo/connection-validation'

  const panelEditor = createXenolithEditorContext()
  let log = $state<Attempt[]>([])

  function push(attempt: Attempt): void {
    log = [attempt, ...log].slice(0, 8)
  }
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { panelEditor.set(e.detail); buildConnectionValidation(e.detail, push) }}
  style="position:absolute;inset:0"
></div>

<XenolithControls position="bottom-left" />

<XenolithPanel position="top-right">
  <div style="display:flex;flex-direction:column;gap:8px;width:230px;">
    <p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--xeno-muted);">Connection rules</p>
    <span style="color:var(--xeno-muted);font-size:11px;line-height:1.5;">
      Pins are typed. Drag <b style="color:var(--xeno-text);">Text</b> → a float input — refused (snaps back).
      Drag <b style="color:var(--xeno-text);">C</b> → <b style="color:var(--xeno-text);">A</b> — blocked (cycle).
    </span>
    <div style="display:flex;flex-direction:column;gap:3px;max-height:168px;overflow:hidden;">
      {#if log.length === 0}
        <span style="color:var(--xeno-muted);font-size:11px;">No attempts yet.</span>
      {/if}
      {#each log as attempt, i (i + attempt.text)}
        <span style={`font-size:11px;font-family:var(--xeno-mono, monospace);color:${attempt.ok ? '#39d98a' : '#ff5b6e'};`}>
          {attempt.ok ? '✓' : '✗'} {attempt.text}
        </span>
      {/each}
    </div>
  </div>
</XenolithPanel>
