// apps/demo-react/src/demos/DiagramDemo.tsx
import { useEffect, useState } from 'react'
import { XenolithGraph, XenolithControls, XenolithPanel, XenolithButton, useEditor, useEdges } from '@xenolith/react'
import { buildDiagram } from '@xenolith/demo/diagram'
import { DemoStage } from '../Layout.js'

// Showcase: edges as a diagramming primitive. Text nodes wired with directional edges — arrowhead
// markers, edge labels (pass / fail / retry), and an animated flowing dash on the main path.
//
// Canon: state lives where it's used. The panel owns `animated` AND owns the side-effect that
// pushes it into the editor, because the panel IS inside <XenolithGraph> — `useEditor()` gives
// it the editor directly. `useEdges()` is the public live edge list — no @internal `editor.graph`.

function DiagramPanel() {
  const editor = useEditor()
  const edges = useEdges()
  const [animated, setAnimated] = useState(true)
  useEffect(() => {
    for (const e of edges) editor.setEdgeOptions(e.id, { animated })
  }, [editor, edges, animated])
  return (
    <XenolithPanel position="top-left" style={{ display: 'flex', flexDirection: 'column', gap: 6, width: 200 }}>
      <p style={{ margin: 0, fontSize: 11, textTransform: 'uppercase', letterSpacing: '.05em', color: 'var(--xeno-muted)' }}>Diagram edges</p>
      <XenolithButton active={animated} style={{ width: '100%' }} onClick={() => setAnimated(!animated)}>
        {animated ? '⏸ Stop flow' : '▶ Animate flow'}
      </XenolithButton>
      <span style={{ color: 'var(--xeno-muted)', fontSize: 11, lineHeight: 1.45 }}>
        Directional edges with arrowheads + labels. The main path animates a flowing dash.
      </span>
    </XenolithPanel>
  )
}

/** Showcase: flowchart-style directional edges (markers, labels, animation). */
export function DiagramDemo(): React.ReactElement {
  return (
    <DemoStage>
      <XenolithGraph className="xeno" resizeToWindow={false} onReady={buildDiagram}>
        <XenolithControls position="bottom-left" />
        <DiagramPanel />
      </XenolithGraph>
    </DemoStage>
  )
}

// apps/site/src/examples/svelte/DiagramDemo.svelte
<!-- Svelte — edges is a store. The effect pushes `animated` onto every current edge. -->
<script lang="ts">
  import { xenolith, createXenolithStores, createXenolithEditorContext } from '@xenolithengine/graph-svelte'
  import { XenolithPanel, XenolithButton, XenolithControls } from '@xenolithengine/graph-svelte/components'
  import type { XenolithEditor } from '@xenolithengine/graph-editor'
  import { buildDiagram } from '@xenolithengine/demo/diagram'

  const stores = createXenolithStores()
  const edges = stores.edges
  const panelEditor = createXenolithEditorContext()
  let editor = $state<XenolithEditor | null>(null)
  let animated = $state(true)

  $effect(() => {
    const live = editor
    const list = $edges
    const on = animated
    if (!live) return
    for (const edge of list) live.setEdgeOptions(edge.id, { animated: on })
  })
</script>

<div
  use:xenolith={{ resizeToWindow: false }}
  onready={(e) => { editor = e.detail; panelEditor.set(e.detail); stores.editor.set(e.detail); buildDiagram(e.detail) }}
  style="position:absolute;inset:0"
></div>

<XenolithControls position="bottom-left" />

<XenolithPanel position="top-left">
  <div style="display:flex;flex-direction:column;gap:6px;width:200px;">
    <p style="margin:0;font-size:11px;text-transform:uppercase;letter-spacing:.05em;color:var(--xeno-muted);">Diagram edges</p>
    <XenolithButton active={animated} style="width:100%" onclick={() => { animated = !animated }}>
      {animated ? '⏸ Stop flow' : '▶ Animate flow'}
    </XenolithButton>
    <span style="color:var(--xeno-muted);font-size:11px;line-height:1.45;">
      Directional edges with arrowheads + labels. The main path animates a flowing dash.
      The toggle writes the edges store through setEdgeOptions.
    </span>
  </div>
</XenolithPanel>
